# Generated by Django 4.2.4 on 2023-08-25 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("profile_id", models.AutoField(primary_key=True, serialize=False)),
                ("status", models.CharField(max_length=20, null=True)),
                ("address", models.CharField(max_length=100, null=True)),
                ("phone", models.CharField(max_length=11, null=True)),
                ("date_of_birth", models.CharField(max_length=11, null=True)),
                ("gender", models.CharField(max_length=11, null=True)),
                (
                    "nationality",
                    models.CharField(
                        choices=[
                            ("Nigeria", "Nigeria"),
                            ("United Kingdom", "United Kingdom"),
                            ("USA", "USA"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Oyo", "Oyo"),
                            ("Abia", "Abia"),
                            ("Ekiti", "Ekiti"),
                            ("Abuja", "Abuja"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("Emergency", "Emergency"),
                            ("Operation & Surgery", "Operation & Surgery"),
                            ("Outdoor Checkup", "Outdoor Checkup"),
                            ("Ambulance Service", "Ambulance Service"),
                            ("Medicine & Pharmacy", "Medicine & Pharmacy"),
                            ("Medical Lab", "Medical Lab"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("B+", "B+"),
                            ("O+", "O+"),
                            ("A-", "A-"),
                            ("B-", "B-"),
                            ("O-", "O-"),
                            ("AB", "AB"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "means_of_identity",
                    models.ImageField(null=True, upload_to="identityImage/"),
                ),
                (
                    "particulars",
                    models.FileField(null=True, upload_to="particularsImage/"),
                ),
                (
                    "profile_passport",
                    models.ImageField(null=True, upload_to="profileImage/"),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("CMD", "CMD"),
                            ("CMAC", "CMAC"),
                            ("HOD", "HOD"),
                            ("HR", "HR"),
                            ("Accountant", "Accountant"),
                            ("Admin", "Admin"),
                            ("Consultant", "Consultant"),
                            ("Resident Doctor", "Resident Doctor"),
                            ("Clerical Staff", "Clerical Staff"),
                            ("Pharmacist", "Pharmacist"),
                            ("Medical Lab Scientist", "Medical Lab Scientist"),
                            ("Scientific Oficer", "Scientific Oficer"),
                        ],
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("Single", "Single"),
                            ("Married", "Married"),
                            ("Engaged", "Engaged"),
                            ("Divorced", "Divorced"),
                        ],
                        max_length=25,
                        null=True,
                    ),
                ),
                ("staff", models.BooleanField(default=False)),
                ("next_of_kin", models.CharField(max_length=20, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
