# Generated by Django 4.2.4 on 2023-08-25 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                ("service_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "service_option",
                    models.CharField(
                        choices=[
                            ("Emergency Care", "Emergency Care"),
                            ("Ambulance service", "Ambulance service"),
                            ("Medicine & Pharmacy", "Medicine & Pharmacy"),
                            ("Operation & Surgery", "Operation & Surgery"),
                            ("Blood Testing", "Blood Testing"),
                            ("Outdoor Checkup", "Outdoor Checkup"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "service_logo",
                    models.ImageField(blank=True, null=True, upload_to="service_logo/"),
                ),
                ("price", models.BigIntegerField()),
                (
                    "description",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "HoD",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
