# Generated by Django 4.2.4 on 2023-08-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("serviceapp", "0002_alter_service_service_option_bookingservice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingservice",
            name="service_option",
            field=models.CharField(
                choices=[
                    ("Emergency Care", "Emergency Care"),
                    ("Ambulance service", "Ambulance service"),
                    ("Medicine & Pharmacy", "Medicine & Pharmacy"),
                    ("Operation & Surgery", "Operation & Surgery"),
                    ("Blood Testing", "Blood Testing"),
                    ("Outdoor Checkup", "Outdoor Checkup"),
                    ("General Health", "General Health"),
                    ("Cardiology", "Cardiology"),
                    ("Dental", "Dental"),
                    ("Neurology", "Neurology"),
                    ("Orthopaedics", "Orthopaedics"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
    ]
