# Generated by Django 4.2.4 on 2023-08-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("serviceapp", "0003_alter_bookingservice_service_option"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingservice",
            name="service_option",
            field=models.IntegerField(),
        ),
    ]
