# Generated by Django 4.2.4 on 2023-08-28 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("serviceapp", "0004_alter_bookingservice_service_option"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookingservice",
            name="service_option",
        ),
        migrations.AddField(
            model_name="bookingservice",
            name="service_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="serviceapp.service",
            ),
            preserve_default=False,
        ),
    ]
