# Generated by Django 4.2.4 on 2023-08-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("serviceapp", "0005_remove_bookingservice_service_option_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookingservice",
            old_name="service_id",
            new_name="service",
        ),
        migrations.AddField(
            model_name="bookingservice",
            name="service_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
